### ISSUE TITLE
Calibration error no ESCAPE_SEQUENCES

### ISSUE THREAD

**Issue by Gerald-Meyers** [sunfounder/picrawler#30]
I was starting the calibration step after installing the needed software on my pi4 and ran into this error. I pressed the `Q` key on accident.

    Traceback (most recent call last):
      File "/home/pi/picrawler/examples/calibration/calibration.py", line 113, in <module>
        cali_helper()
      File "/home/pi/picrawler/examples/calibration/calibration.py", line 107, in cali_helper
        elif key == readchar.key.CTRL_C or key in readchar.key.ESCAPE_SEQUENCES:
    AttributeError: module 'readchar._posix_key' has no attribute 'ESCAPE_SEQUENCES

**Comment by Lovmong** [comment]
Fixed
